### PR TITLE
Rhel8 support

### PR DESCRIPTION
**Pull request by AaronZhouYu**
Use 'sudo yum check-update -q" command to replace the original python library which has not been supported in RHEL8

### CODE REVIEW

**Comment by chris-rock** [comment]
Thank you @AaronZhouYu Have you tested this for Rhel 6 and 7?

In addition I would prefer if the parsing logic is written in Ruby, this would make it more adoptable and depend less on external commands

**Comment by AaronZhouYu** [comment]
Hi @chris-rock , I have tested on RHEL 7 and 8, but not RHEL 6.
The parsing logic is not written in Ruby.

**Comment by Stromweld** [comment]
This is fixed in #57

**Comment by schurzi** [comment]
superseeded by #57

**Pull request closed without merging**
